# Fine-tune an LM on the enron text dataset.
# enron-qwen2.5-14b-Inst-undefended.yml

dataset_args:
  dataset_path: data/enron/enron.py
  dataset_mode: undefended
  sample_duplication_rate: 1
  pseudonymize: False  # for non-scrubbing, disabling this can save time in data loading.

trainer_args:
  output_dir: ./results/enron-qwen2.5-14b-Inst-undefended/
  evaluation_strategy: steps
  eval_steps: 200
  logging_steps: 10
  save_total_limit: 2
  save_strategy: steps
  save_steps: 500  
  overwrite_output_dir: True
  callback_after_n_steps: 100
  num_train_epochs: 3
  gradient_accumulation_steps: 4  
  per_device_train_batch_size: 2  
  per_device_eval_batch_size: 2
  bf16: True
  bf16_full_eval: True
  #fp16: True
  #fp16_full_eval: True
  learning_rate: 0.00001
  resume_from_checkpoint: False
  deepspeed: configs/fine-tune/deepspeed_lora_stage1.json  
  do_train: True

model_args:
  # model_ckpt: "~/"  # Use local path if available
  architecture: "Qwen/Qwen2.5-14B-Instruct" # Hugging Face model path
  pre_trained: True
  device_map: auto
  peft: lora  
  lora_r: 8  
  lora_alpha: 32  
  lora_dropout: 0.1  

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
